"""initial kb schema

Revision ID: c9350a4b0843
Revises: 
Create Date: 2026-04-27 00:45:27.301224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9350a4b0843'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kb_misconception_candidate',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=True),
    sa.Column('dialog_id', sa.String(length=128), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('student_text', sa.Text(), nullable=False, comment='触发该候选的学生原话'),
    sa.Column('suggested_misconception_json', sa.Text(), nullable=False, comment='JSON: LLM 生成的迷思建议结构（subject/stage/key_point/...）'),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reviewer_id', sa.String(length=128), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=False),
    sa.Column('merged_into_id', sa.String(length=128), nullable=True, comment="status='merged' 时指向正式 misconception id"),
    sa.CheckConstraint("status IN ('candidate', 'reviewing', 'approved', 'rejected', 'merged')", name='ck_candidate_status'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kb_misconception_candidate', schema=None) as batch_op:
        batch_op.create_index('ix_candidate_status', ['status', 'detected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_kb_misconception_candidate_detected_at'), ['detected_at'], unique=False)

    op.create_table('kb_observation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=True),
    sa.Column('dialog_id', sa.String(length=128), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('theory_id', sa.String(length=64), nullable=True),
    sa.Column('trait_key', sa.String(length=64), nullable=True),
    sa.Column('persona_id', sa.String(length=128), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=False, comment='JSON 自由结构；event_type 决定 schema'),
    sa.CheckConstraint("event_type IN ('theory_confirmed', 'theory_violated', 'misconception_candidate', 'anchor_added', 'anchor_removed', 'candidate_reviewed', 'evolution')", name='ck_observation_event_type'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kb_observation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kb_observation_observed_at'), ['observed_at'], unique=False)
        batch_op.create_index('ix_observation_event', ['event_type', 'observed_at'], unique=False)
        batch_op.create_index('ix_observation_persona', ['persona_id'], unique=False)
        batch_op.create_index('ix_observation_theory', ['theory_id', 'trait_key'], unique=False)

    op.create_table('kb_theory',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name_zh', sa.String(length=64), nullable=False),
    sa.Column('name_en', sa.String(length=128), nullable=False),
    sa.Column('scholar', sa.String(length=128), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('school', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('references_json', sa.Text(), nullable=False, comment='JSON 序列化 list[str]'),
    sa.Column('applies_to_json', sa.Text(), nullable=False, comment='JSON: {persona: bool, misconception: bool, rubric: bool}'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kb_theory_trait',
    sa.Column('theory_id', sa.String(length=64), nullable=False),
    sa.Column('trait_key', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('operational_rules_json', sa.Text(), nullable=False, comment='JSON 序列化 list[str] 行为准则'),
    sa.ForeignKeyConstraint(['theory_id'], ['kb_theory.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('theory_id', 'trait_key')
    )
    op.create_table('kb_theory_anchor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('theory_id', sa.String(length=64), nullable=False),
    sa.Column('trait_key', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.String(length=128), nullable=False, comment='persona name / misconception id / rubric 维度 key'),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("target_type IN ('persona', 'misconception', 'rubric_dim')", name='ck_anchor_target_type'),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_anchor_confidence_range'),
    sa.ForeignKeyConstraint(['theory_id', 'trait_key'], ['kb_theory_trait.theory_id', 'kb_theory_trait.trait_key'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('theory_id', 'trait_key', 'target_type', 'target_id', name='uq_anchor_trait_target')
    )
    with op.batch_alter_table('kb_theory_anchor', schema=None) as batch_op:
        batch_op.create_index('ix_anchor_target', ['target_type', 'target_id'], unique=False)
        batch_op.create_index('ix_anchor_theory', ['theory_id', 'trait_key'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kb_theory_anchor', schema=None) as batch_op:
        batch_op.drop_index('ix_anchor_theory')
        batch_op.drop_index('ix_anchor_target')

    op.drop_table('kb_theory_anchor')
    op.drop_table('kb_theory_trait')
    op.drop_table('kb_theory')
    with op.batch_alter_table('kb_observation', schema=None) as batch_op:
        batch_op.drop_index('ix_observation_theory')
        batch_op.drop_index('ix_observation_persona')
        batch_op.drop_index('ix_observation_event')
        batch_op.drop_index(batch_op.f('ix_kb_observation_observed_at'))

    op.drop_table('kb_observation')
    with op.batch_alter_table('kb_misconception_candidate', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kb_misconception_candidate_detected_at'))
        batch_op.drop_index('ix_candidate_status')

    op.drop_table('kb_misconception_candidate')
    # ### end Alembic commands ###
